//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string POSITION { get; set; }
    }
}
