//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class INTERVIEW
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<int> POSITION { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public Nullable<int> EMPLOYEE_POSITION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> TEST_TASK_END_DATE { get; set; }
    }
}
